{ stdenv, lib, fetchurl, meson, ninja, pkg-config, wayland, git
, alsaLib, gnome3, gtk-layer-shell, pulseaudio, wayfire, wf-config
}:

stdenv.mkDerivation rec {
  pname = "wf-shell";
  version = "0.5.0";

  # > Note to packagers: do not use the autogenerated "Source code"
  # > archives from GitHub, but the wf-shell-0.4.0.tar.xz file.
  src = fetchurl {
    url = "https://github.com/WayfireWM/wf-shell/releases/download/${version}/wf-shell-${version}.tar.xz";
    sha256 = "1w4jhy84v9ky9s1iw36msn8189a3pwkvvivyhl44pfc4fy31wj7s";
  };

  nativeBuildInputs = [ meson ninja pkg-config wayland ];
  buildInputs = [
    alsaLib gnome3.gtkmm gtk-layer-shell pulseaudio wayfire wf-config
  ];

  mesonFlags = [ "--sysconfdir" "/etc" ];

  meta = with lib; {
    homepage = "https://github.com/WayfireWM/wf-shell";
    description = "GTK3-based panel for Wayfire";
    license = licenses.mit;
    maintainers = with maintainers; [ qyliss wucke13 ];
    platforms = platforms.unix;
  };
}
